### ISSUE TITLE
Improve performance with routing 

### ISSUE THREAD

**Issue by mernaAlghannam** [BU-Spark/se-bch-als-resource-app#28]
- Use dynamic routing
- -More usage of useMemo and useCallBack

**Comment by mernaAlghannam** [comment]
In dev branch, we used dynamic routes because it makes our code cleaner and easier to follow. In addition, it creates a page for each question. However, it currently can only be deployed as a dynamic website. To make it a static site, next team would need to usegetstatic paths to generate all pages during build. (Note: our teammate believes we should keep it dynamic as generating all pages at once wastes resources)

Our page rendering performance can be improved by using possibly dynamic routes (working starter code in dev branch). In addition, the back button is difficult to press. Thus, usecallback can also be useful there.

**Comment by chien-ying** [comment]
> * Use dynamic routing
> * -More usage of useMemo and useCallBack

In the dev branch, we utilize dynamic routes in a way where each page represents one page.
Dynamic routes work as follows:
The folder src/pages/question indicates the page of question, under that folder, there is a file [id].tsx and you can reference this id from the code using the useRouter hook. The url for this question page will look like <base_url>/question/[id]
So as the folder src/pages/solution
