### ISSUE TITLE
Remove useEffect that runs once when page loads

### ISSUE THREAD

**Issue by mernaAlghannam** [BU-Spark/se-bch-als-resource-app#30]
UseEffect gets called twice during dev. Therefore, the back button may appear sooner, cause the page title not to render correctly. Useeffect is not a good option. Thus, we solved this in dev branch by using dynamic routes. It reroute to previous page when user clicks back button. https://github.com/BU-Spark/se-bch-als-resource-app/blob/f7e31696002a8e55ef57001b375a0220a8fc169f/code/src/pages/QuestionairePage.tsx#L93

**Comment by ArkashJ** [comment]
We removed CloseIssue
