### ISSUE TITLE
Strapi Deployement

### ISSUE THREAD

**Issue by mernaAlghannam** [BU-Spark/se-bch-als-resource-app#31]
Strapi is deployed in a seperate branch because the site can lose all images and videos if redeployed. I used railway and postgress for production, following this link https://dev.to/yinks/how-to-create-and-deploy-a-strapi-project-on-railway-3kja 

It currently only saves text, but in order to deploy images, you need to create a seperate deployment. Since local uses sqllite, I added a seperate config for production db https://github.com/BU-Spark/se-bch-als-resource-app/tree/strapiDeployment/backend-strapi/config/env/production 

In the meantime, do not push into strapiDeploy branch. Create a new branch if you must use it.

**Comment by chrisharris02** [comment]
Not needed after Typeform migration.
