### ISSUE TITLE
Adding Database

### ISSUE THREAD

**Issue by ArkashJ** [BU-Spark/se-bch-als-resource-app#32]
We have implemented code for a database in here (MongoDB) specifically however we never implemented a save option because the client did not require us to at the time of writing this article. However, for future teams, they can look at our code and implement any database they like by making small tweaks to it.

We do wish we implemented the database however a problem was having a shared mongo cluster. For future teams choosing database that is easily accessible and cheap will be useful.

We have a server.js file and code in the utils folder for the database in branch Arkash/NewBackendSave

**Comment by chrisharris02** [comment]
We can't use a database to store any saved information because of HIPAA restrictions.
