### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by ArkashJ** [BU-Spark/se-bch-als-resource-app#33]
We added unit tests for rendering data however future teams can add more tests to check routing, apis, data loading etc. 
Writing and running the tests added a lot of bugs however we believe we fixed them. Future teams can read our docs for reference.

The readME has docs for the tests and for all components and apis

**Comment by chrisharris02** [comment]
We added more tests around the Typeform migration and relating to the UI changes from this semester.
