### ISSUE TITLE
Create a backend that calls the api url for better security

### ISSUE THREAD

**Issue by mernaAlghannam** [BU-Spark/se-bch-als-resource-app#35]
If you use process.env for url in frontend, people can still view the full name of the api url by checking network. Therefore, you must create a backend endpoint that makes the direct api calls. Then, the fronend will call the backend. Furthermore, make sure to make the api url an env variable in the backend. You can consider other other options for better security.

**Comment by chrisharris02** [comment]
We have a NextJS backend api in /pages/api/retrieveQuestions
