### ISSUE TITLE
site/questions/<random number> in dev branch should return 404 error if that question id does not exist

### ISSUE THREAD

**Issue by mernaAlghannam** [BU-Spark/se-bch-als-resource-app#37]
Dev branch uses dynamic routes for better performance and to ensure site is stateless. If you chose to use it, Test what happens if you called site/questions/<random number> in dev branch, then handle error accordingly. It may still show a site and it should give a 404 error since it should not exist if there is no question what that id

You should also try  site/solutions/<random number>

**Comment by chrisharris02** [comment]
Not needed after Typeform migration.
